### ISSUE TITLE
Where to declare the angular app

### ISSUE THREAD

**Issue by uriva** [netanelgilad/meteor-angular-server#1]
First off, what you're doing is very cool.

Some questions.
- Should I include a dependency to `angular-server`?
- Should I declare my app both on client and server (or outside of them both), or just on client directory?

This is my current declaration, outside of both directories, so it will run everywhere. 

```
angular.module('myApp', ['angular-server', 'angular-meteor', 'ui.router', 'ngMaterial']);
```

Currently I'm getting this error:
`Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by netanelgilad** [comment]
Having the deceleration in both client and server is exactly what you need. What you are probably experiencing is that the module is defined after it is used because of Meteor's load order.
Try creating an app.js file in a lib folder, to make sure it loads first.
Also check out the example repo: https://github.com/netanelgilad/angular-server-example

About the dependency, you should depend on angular-meteor 0.9.0-alpha.2, it takes care of adding angular-server and doing a lot of other stuff...

**Comment by uriva** [comment]
Ok, now I seem to be getting errors regarding deps like ng-material and ui.router.

```
Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument
```

Although I have the packages in my meteor project depends on them + I have them in my app declaration.

I see that in your example there is only one dep - angular-meteor.
Should I somehow transfer my client side deps to the client directory?

**Comment by netanelgilad** [comment]
Yep. So since you have dependencies which are not server related at all, you need to seperate your server depedencies from your client ones. I'm still thinking what should be the best practice for this but I'm thinking something along these lines:

``` js
// lib/app.js
var deps = ['angular-meteor', ....];

if (Meteor.isServer) {
  deps.concat([/* server deps */]);
}
else {
  deps.concat([/* client deps */]);
}

angular.module('myApp', deps);
```

what do you think?

**Comment by uriva** [comment]
Ah I see. :+1: 

Maybe run over angular.module?
Or add a function...

``` javascript
angular.stack = function(moduleName, jointDeps, clientDeps, serverDeps) {
  var deps;
  if (Meteor.isServer) {
    deps = jointDeps.concat(serverDeps);
  } else {
    deps = jointDeps.concat(clientDeps);
  }
  angular.module(moduleName, deps);
};
```

**Comment by uriva** [comment]
This works great in browser. On mobile I'm getting:
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`
Do I need to permit these somehow? Doesn't the meteor framework already do so?

**Comment by netanelgilad** [comment]
Haven't encountered this error, and I ran it on mobile. It seems unrelated to me, but if you can share a reproduction i'll have look.. :)

**Comment by uriva** [comment]
Yup. Just something to do with a package I had I think.
Everything's working now.
Thanks!
