### ISSUE TITLE
ui.router breaks when adding package

### ISSUE THREAD

**Issue by jaypanares** [netanelgilad/meteor-angular-server#5]
When I add this package and move my app module code to lib/app.js

```
var deps = [];

if (Meteor.isClient) {
  deps = [
    'angular-meteor',
    'ui.router',
    'underscore',
    'myApp.moduleA'
  ];
}else {
  deps = ['angular-meteor'];
}

angular
  .module('myApp', deps);
```

ui.router seems to break.  I'm seeing no errors on both client and server but no routes are getting loaded.  Is there something I missed?

Thanks and great work btw

**Comment by netanelgilad** [comment]
Hey @jaypanares,
care to share a reproduction? I can have a look. From you posted I can't think of a reason why it won't work.
