### ISSUE TITLE
not able to pass params to $http.get when running on server.

### ISSUE THREAD

**Issue by haukurk** [netanelgilad/meteor-angular-server#6]
I've been testing out to make server side $http calls with AngularJS, and so far it has not been working out.

I have these following two services, one client side and one server side:

Service in server folder:

```
angular.module('testApp')
  .service('TestServerService', function ($http) {
    var service = {};

    // public members
    function SearchTranslations(searchParams) {
        return $http.get("http://testapi.hauxi.is/api/testmethod", { params: searchParams })
                    .then(handleSuccess, handleError('Error when retreiving data from api.'));
    }

    // private members
    ...
    ...

    service.SearchTranslations = SearchTranslations;
    return service;
  })
  .config(function (ServerAPIProvider) { // Expose it to the API Provider.
    ServerAPIProvider.register('TranslationService');
  });
```

Service in client folder:

```
angular.module('testApp')
  .service('TestClientService', function ($http) {
    var service = {};

    // public members
    function SearchTranslations(searchParams) {
        return $http.get("http://testapi.hauxi.is/api/testmethod", { params: searchParams })
                    .then(handleSuccess, handleError('Error when retreiving data from api.'));
    }

    // private members
    .... 
    ....

    service.SearchTranslations = SearchTranslations;
    return service;
  });
```

The client service works perfectly like always, but the server service discards the params passed to the function.

In my case searchParams can be like:

```
httpParams = {
   "filter[limit]": 100,
   "filter[where][word][like]": "searching%"
}
```

When using the client side service I see these logs in on the API server:
[21/Jul/2015:19:00:00 -0400] "GET /api/translations?filter[where][word[like]=hauku%&filter[limit]=100 HTTP/1.1" 200 153 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"

When using the server side service I see these logs on the API server:
[21/Jul/2015:20:27:58 -0400] "GET /api/translations HTTP/1.1" 200 15418540 "-" "-"

Note, that no params are used when using the server service..

Any idea why this is happening?

**Comment by netanelgilad** [comment]
Hey @haukurk,
I haven't been around for the last 3 months, (traveling) so sorry for not answering.
Did you close this issue cause it eventually worked for you or have you gone for another solution? 
I don't remember if I added support for http params yet in angular-server, though it is definitely possible. If this is still relevant, you can re-open the issue and I'll take care of it.

**Comment by haukurk** [comment]
Still a issue. I think. :)
